/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessaoExpiradaRouteImport } from './routes/sessao-expirada'
import { Route as PagamentoErroRouteImport } from './routes/pagamento-erro'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErroRouteImport } from './routes/erro'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedContaPedidosRouteImport } from './routes/_authenticated/conta.pedidos'
import { Route as AuthenticatedContaNotificacoesRouteImport } from './routes/_authenticated/conta.notificacoes'
import { Route as AuthenticatedContaFidelidadeRouteImport } from './routes/_authenticated/conta.fidelidade'
import { Route as AuthenticatedContaFavoritosRouteImport } from './routes/_authenticated/conta.favoritos'
import { Route as AuthenticatedContaEnderecosRouteImport } from './routes/_authenticated/conta.enderecos'
import { Route as AdminAdminProdutosRouteImport } from './routes/_admin/admin.produtos'
import { Route as AdminAdminPedidosRouteImport } from './routes/_admin/admin.pedidos'
import { Route as AdminAdminCuponsRouteImport } from './routes/_admin/admin.cupons'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin/admin.configuracoes'
import { Route as AdminAdminClientesRouteImport } from './routes/_admin/admin.clientes'
import { Route as AdminAdminCategoriasRouteImport } from './routes/_admin/admin.categorias'

const SessaoExpiradaRoute = SessaoExpiradaRouteImport.update({
  id: '/sessao-expirada',
  path: '/sessao-expirada',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoErroRoute = PagamentoErroRouteImport.update({
  id: '/pagamento-erro',
  path: '/pagamento-erro',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErroRoute = ErroRouteImport.update({
  id: '/erro',
  path: '/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedContaPedidosRoute =
  AuthenticatedContaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedContaRoute,
  } as any)
const AuthenticatedContaNotificacoesRoute =
  AuthenticatedContaNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedContaRoute,
  } as any)
const AuthenticatedContaFidelidadeRoute =
  AuthenticatedContaFidelidadeRouteImport.update({
    id: '/fidelidade',
    path: '/fidelidade',
    getParentRoute: () => AuthenticatedContaRoute,
  } as any)
const AuthenticatedContaFavoritosRoute =
  AuthenticatedContaFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedContaRoute,
  } as any)
const AuthenticatedContaEnderecosRoute =
  AuthenticatedContaEnderecosRouteImport.update({
    id: '/enderecos',
    path: '/enderecos',
    getParentRoute: () => AuthenticatedContaRoute,
  } as any)
const AdminAdminProdutosRoute = AdminAdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPedidosRoute = AdminAdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCuponsRoute = AdminAdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClientesRoute = AdminAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCategoriasRoute = AdminAdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/erro': typeof ErroRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/manutencao': typeof ManutencaoRoute
  '/pagamento-erro': typeof PagamentoErroRoute
  '/sessao-expirada': typeof SessaoExpiradaRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/conta': typeof AuthenticatedContaRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/categorias': typeof AdminAdminCategoriasRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/cupons': typeof AdminAdminCuponsRoute
  '/admin/pedidos': typeof AdminAdminPedidosRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/conta/enderecos': typeof AuthenticatedContaEnderecosRoute
  '/conta/favoritos': typeof AuthenticatedContaFavoritosRoute
  '/conta/fidelidade': typeof AuthenticatedContaFidelidadeRoute
  '/conta/notificacoes': typeof AuthenticatedContaNotificacoesRoute
  '/conta/pedidos': typeof AuthenticatedContaPedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/erro': typeof ErroRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/manutencao': typeof ManutencaoRoute
  '/pagamento-erro': typeof PagamentoErroRoute
  '/sessao-expirada': typeof SessaoExpiradaRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/conta': typeof AuthenticatedContaRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/categorias': typeof AdminAdminCategoriasRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/cupons': typeof AdminAdminCuponsRoute
  '/admin/pedidos': typeof AdminAdminPedidosRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/conta/enderecos': typeof AuthenticatedContaEnderecosRoute
  '/conta/favoritos': typeof AuthenticatedContaFavoritosRoute
  '/conta/fidelidade': typeof AuthenticatedContaFidelidadeRoute
  '/conta/notificacoes': typeof AuthenticatedContaNotificacoesRoute
  '/conta/pedidos': typeof AuthenticatedContaPedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/erro': typeof ErroRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/manutencao': typeof ManutencaoRoute
  '/pagamento-erro': typeof PagamentoErroRoute
  '/sessao-expirada': typeof SessaoExpiradaRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/conta': typeof AuthenticatedContaRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_admin/admin/categorias': typeof AdminAdminCategoriasRoute
  '/_admin/admin/clientes': typeof AdminAdminClientesRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/cupons': typeof AdminAdminCuponsRoute
  '/_admin/admin/pedidos': typeof AdminAdminPedidosRoute
  '/_admin/admin/produtos': typeof AdminAdminProdutosRoute
  '/_authenticated/conta/enderecos': typeof AuthenticatedContaEnderecosRoute
  '/_authenticated/conta/favoritos': typeof AuthenticatedContaFavoritosRoute
  '/_authenticated/conta/fidelidade': typeof AuthenticatedContaFidelidadeRoute
  '/_authenticated/conta/notificacoes': typeof AuthenticatedContaNotificacoesRoute
  '/_authenticated/conta/pedidos': typeof AuthenticatedContaPedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/carrinho'
    | '/checkout'
    | '/erro'
    | '/login'
    | '/loja'
    | '/manutencao'
    | '/pagamento-erro'
    | '/sessao-expirada'
    | '/admin'
    | '/conta'
    | '/produto/$slug'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/conta/enderecos'
    | '/conta/favoritos'
    | '/conta/fidelidade'
    | '/conta/notificacoes'
    | '/conta/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/carrinho'
    | '/checkout'
    | '/erro'
    | '/login'
    | '/loja'
    | '/manutencao'
    | '/pagamento-erro'
    | '/sessao-expirada'
    | '/admin'
    | '/conta'
    | '/produto/$slug'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/conta/enderecos'
    | '/conta/favoritos'
    | '/conta/fidelidade'
    | '/conta/notificacoes'
    | '/conta/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/acesso-negado'
    | '/carrinho'
    | '/checkout'
    | '/erro'
    | '/login'
    | '/loja'
    | '/manutencao'
    | '/pagamento-erro'
    | '/sessao-expirada'
    | '/_admin/admin'
    | '/_authenticated/conta'
    | '/produto/$slug'
    | '/_admin/admin/categorias'
    | '/_admin/admin/clientes'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/cupons'
    | '/_admin/admin/pedidos'
    | '/_admin/admin/produtos'
    | '/_authenticated/conta/enderecos'
    | '/_authenticated/conta/favoritos'
    | '/_authenticated/conta/fidelidade'
    | '/_authenticated/conta/notificacoes'
    | '/_authenticated/conta/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ErroRoute: typeof ErroRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  ManutencaoRoute: typeof ManutencaoRoute
  PagamentoErroRoute: typeof PagamentoErroRoute
  SessaoExpiradaRoute: typeof SessaoExpiradaRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessao-expirada': {
      id: '/sessao-expirada'
      path: '/sessao-expirada'
      fullPath: '/sessao-expirada'
      preLoaderRoute: typeof SessaoExpiradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-erro': {
      id: '/pagamento-erro'
      path: '/pagamento-erro'
      fullPath: '/pagamento-erro'
      preLoaderRoute: typeof PagamentoErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erro': {
      id: '/erro'
      path: '/erro'
      fullPath: '/erro'
      preLoaderRoute: typeof ErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/conta/pedidos': {
      id: '/_authenticated/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof AuthenticatedContaPedidosRouteImport
      parentRoute: typeof AuthenticatedContaRoute
    }
    '/_authenticated/conta/notificacoes': {
      id: '/_authenticated/conta/notificacoes'
      path: '/notificacoes'
      fullPath: '/conta/notificacoes'
      preLoaderRoute: typeof AuthenticatedContaNotificacoesRouteImport
      parentRoute: typeof AuthenticatedContaRoute
    }
    '/_authenticated/conta/fidelidade': {
      id: '/_authenticated/conta/fidelidade'
      path: '/fidelidade'
      fullPath: '/conta/fidelidade'
      preLoaderRoute: typeof AuthenticatedContaFidelidadeRouteImport
      parentRoute: typeof AuthenticatedContaRoute
    }
    '/_authenticated/conta/favoritos': {
      id: '/_authenticated/conta/favoritos'
      path: '/favoritos'
      fullPath: '/conta/favoritos'
      preLoaderRoute: typeof AuthenticatedContaFavoritosRouteImport
      parentRoute: typeof AuthenticatedContaRoute
    }
    '/_authenticated/conta/enderecos': {
      id: '/_authenticated/conta/enderecos'
      path: '/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof AuthenticatedContaEnderecosRouteImport
      parentRoute: typeof AuthenticatedContaRoute
    }
    '/_admin/admin/produtos': {
      id: '/_admin/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminAdminProdutosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/pedidos': {
      id: '/_admin/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminAdminPedidosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/cupons': {
      id: '/_admin/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminAdminCuponsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/clientes': {
      id: '/_admin/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminAdminClientesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/categorias': {
      id: '/_admin/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminAdminCategoriasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminCategoriasRoute: typeof AdminAdminCategoriasRoute
  AdminAdminClientesRoute: typeof AdminAdminClientesRoute
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminCuponsRoute: typeof AdminAdminCuponsRoute
  AdminAdminPedidosRoute: typeof AdminAdminPedidosRoute
  AdminAdminProdutosRoute: typeof AdminAdminProdutosRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminCategoriasRoute: AdminAdminCategoriasRoute,
  AdminAdminClientesRoute: AdminAdminClientesRoute,
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminCuponsRoute: AdminAdminCuponsRoute,
  AdminAdminPedidosRoute: AdminAdminPedidosRoute,
  AdminAdminProdutosRoute: AdminAdminProdutosRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedContaRouteChildren {
  AuthenticatedContaEnderecosRoute: typeof AuthenticatedContaEnderecosRoute
  AuthenticatedContaFavoritosRoute: typeof AuthenticatedContaFavoritosRoute
  AuthenticatedContaFidelidadeRoute: typeof AuthenticatedContaFidelidadeRoute
  AuthenticatedContaNotificacoesRoute: typeof AuthenticatedContaNotificacoesRoute
  AuthenticatedContaPedidosRoute: typeof AuthenticatedContaPedidosRoute
}

const AuthenticatedContaRouteChildren: AuthenticatedContaRouteChildren = {
  AuthenticatedContaEnderecosRoute: AuthenticatedContaEnderecosRoute,
  AuthenticatedContaFavoritosRoute: AuthenticatedContaFavoritosRoute,
  AuthenticatedContaFidelidadeRoute: AuthenticatedContaFidelidadeRoute,
  AuthenticatedContaNotificacoesRoute: AuthenticatedContaNotificacoesRoute,
  AuthenticatedContaPedidosRoute: AuthenticatedContaPedidosRoute,
}

const AuthenticatedContaRouteWithChildren =
  AuthenticatedContaRoute._addFileChildren(AuthenticatedContaRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ErroRoute: ErroRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  ManutencaoRoute: ManutencaoRoute,
  PagamentoErroRoute: PagamentoErroRoute,
  SessaoExpiradaRoute: SessaoExpiradaRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
